name: build

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t angrymaciek/angry-runner:latest .

      - name: Check the current user info
        run: id

      - name: Run commands in container as root
        run: |
          docker run --name angry-runner -e HOSTUID=`id -u $USER` angry-runner:latest id
          docker rm angry-runner

      - name: Run commands in container as angryuser
        run: |
          docker run --name angry-runner -e HOSTUID=`id -u $USER` angry-runner:latest gosu angryuser id
          docker rm angry-runner

...
