name: build

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        
      - name: test user
        run: |
          whoami
          id

      - name: Build Docker image
        run: docker build -t angrymaciek/angry-runner:latest .

...
